######################################
#### analysis-specific parameters ####
######################################

analysis:
  name: AZ_exercise
  organism: "human" #supports "human"/"mouse"
  genomeBuild: "hg38"

samples:
  - SRR5223500
  - SRR5223505
  - SRR5223522
  - SRR5223543
  - SRR5223547
  - SRR5223570

stimulation:
  - control
  - treated
  - control
  - control
  - treated
  - treated

# flags and programs.
useSRA: FALSE # True if input consists of SRA IDs.
quantification: salmon   # supports "salmon" and "rsem".
countMatrix: TRUE # Generates count/TPM matrix based on input samples.
deconvolution: TRUE # Runs deconvolution, currently set up for human colon tissue.
pairedEnd: TRUE # TRUE if input samples were sequenced paired-end

#############################
#### Software parameters ####
#############################

# http://gensoft.pasteur.fr/docs/cutadapt/1.18/guide.html#paired-end
cutadapt: # Current hard coded for Illumina TruSeq adapters. Modify -a/-A for other adapters
  a: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  A: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
  qualityCutoff: 10
  minimumLength: 20

# https://raw.githubusercontent.com/alexdobin/STAR/master/doc/STARmanual.pdf
star:
  threads: 8
  genomeLoad: LoadAndRemove
  outSAMtype: BAM
  quantMode: GeneCounts
  readFilesCommand: "gunzip -c"
  sjdbOverhang: 49

# https://salmon.readthedocs.io/en/latest/salmon.html
salmon:
  libType: A # IU
  threads: 8
  numBootstraps: 30
  otherFlags: "--seqBias --gcBias --validateMappings"

rsem:
  threads: 8
  reference: reference/hg38_rsem/rsem_hg38
  otherFlags: "--paired-end --star --output-genome-bam \
                --keep-intermediate-files  --star-gzipped-read-file"

fastqc:
  threads: 1

multiqc:
  configFile: bin/multiqc_config_hg38.yaml

rseqc:
  modelFile: bin/hg38.HouseKeepingGenes.bed

#genome indexes
human:
  build:
  samlonIndex:
  starIndex:

mouse:
  build:
  salmonIndex:
  starIndex:
