######################################
#### analysis-specific parameters ####
######################################

analysis:
  name: AZ_exercise
  organism: "human" #supports "human"/"mouse"
  genomeBuild: "hg38"

samples:
  - SRR5223500
  - SRR5223505
  - SRR5223522
  - SRR5223543
  - SRR5223547
  - SRR5223570

stimulation:
  - control
  - treated
  - control
  - control
  - treated
  - treated

#############################
#### Software parameters ####
#############################


star:
#  sjdbOverhang: 74
  cores: 8
  genomeLoad: LoadAndRemove
  outSAMtype: BAM Unsorted
  quantMode: GeneCounts

rsem:
  threads: 8
  reference: reference/hg38_rsem/rsem_hg38

fastqc:
  t: 1

multiqc:
  configFile: bin/multiqc_config_hg38.yaml

rseqc:
  modelFile: bin/hg38.HouseKeepingGenes.bed

#genome indexes
