######################################
#### analysis-specific parameters ####
######################################

analysis:
  name: AZ_exercise
  organism: "human" #supports "human"/"mouse"
  genomeBuild: "hg38"

samples:
  - SRR5223500
  - SRR5223505

stimulation:
  - control
  - treated

# flags and programs.
useSRA: FALSE # True if input consists of SRA IDs.
quantification: salmon  # supports "salmon" and "rsem".
countMatrix: TRUE # Generates count/TPM matrix based on input samples.
deconvolution: TRUE # Runs deconvolution, currently set up for human colon tissue.
pairedEnd: TRUE # TRUE if input samples were sequenced paired-end

#############################
#### Software parameters ####
#############################

# https://cutadapt.readthedocs.io/en/stable/
cutadapt: # Current hard coded for Illumina TruSeq adapters. Modify -a/-A for other adapters
  a: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  A: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
  qualityCutoff: 10
  minimumLength: 20

# https://raw.githubusercontent.com/alexdobin/STAR/master/doc/STARmanual.pdf
star:
  threads: 8
  genomeLoad: LoadAndRemove
  outSAMtype: "BAM SortedByCoordinate"
  quantMode: GeneCounts
  readFilesCommand: "gunzip -c"
  sjdbOverhang: 49

# https://salmon.readthedocs.io/en/latest/salmon.html
salmon:
  libType: ISR
  threads: 8
  numBootstraps: 30
  otherFlags: "--seqBias --gcBias --validateMappings --writeUnmappedNames"

rsem:
  threads: 8
  reference: reference/hg38_rsem/rsem_hg38
  otherFlags: "--paired-end --star --output-genome-bam --keep-intermediate-files  --star-gzipped-read-file"

fastqc:
  threads: 1

multiqc:
  configFile: bin/multiqc_config_hg38.yaml

rseqc:
  modelFile: bin/hg38.HouseKeepingGenes.bed

#genome indexes - !!!STAR/SALMON INDEXES BUILT FOR PRIMARLY 50BP READS!!!
#commands use to build these indexes are in X SOP

hg19:
  salmonIndex: /proj/fureylab/genomes/human/hg19_reference/hg19_salmon_1.1.0
  starIndex: /proj/fureylab/genomes/human/hg19_reference/hg19_star_2.7.3a
  rsemIndex: /proj/fureylab/genomes/human/hg19_reference/hg19_star_2.7.3a
  rseqcModel: bin/hg19.HouseKeepingGenes.bed
  multiqcConfig: bin/multiqc_config_hg19.yaml
hg38:
  salmonIndex: /proj/fureylab/genomes/human/hg38_reference/hg38_salmon_1.1.0
  starIndex: /proj/fureylab/genomes/human/hg38_reference/hg38_star_2.7.3a
  rsemIndex: /proj/fureylab/genomes/human/hg38_reference/hg38_star_2.7.3a
  rseqcModel: bin/hg38.HouseKeepingGenes.bed
  multiqcConfig: bin/multiqc_config_hg38.yaml

# mouse:
#   build:
#     salmonIndex:
#     starIndex:
