# For use with the Furey RNA-seq Snakemake pipeline 1.1

# 1. Fill in "analysis" fields
# 2. Add samples for analysis in "samples" section
# 3. Double check flags and options
# 4. Update salmon's "libType", if needed (https://salmon.readthedocs.io/en/latest/library_type.html). Currently set for automatic detection.

######################################
#### analysis-specific parameters ####
######################################

###
# Analysis set up
###

analysis:
  projectName: "Furey_analysis"
  # summary files will be produced using this name.
  # NOTE: Chose an informative name! e.g.:
  #  - "Crohns_human_colon"
  #  - "ozone_cc"
  #  - "Crohns_mouse_macrophage"
  # NOTE: This name must NOT contain whitespace charcters!

  organism: "human"
  #supports "human"/"mouse"

  genomeBuild: "hg38"
  #supports hg38 (GRCh38), hg19 (GRCh37), mm10, and CC027

  readLength: 50
  #length of reads in seq run. Supports 50, 75, 150.

# NOTE: support for additional organisms be added by creating indexs and
# required files in the "genome indexes" section at the bottom of the configFn
# The Pipeline Indexing SOP can be used to guide the creation of these files.

# For local file run, paths need to provided to the base sample directory.
# The pipeline expects this sample directory to contain a "fastq" directory with
# two gzipped fastq files.
# At the time of creating the pipeline, all fastq files could be identifed as
# read1/read2 through "*_RX_*" or "*X.f*q.gz" regexs, where X is 1 or 2.
samples:
  - /proj/fureylab/data/RNA-seq/human/colon_tissue/nonIBD/172/
  - /proj/fureylab/data/RNA-seq/human/colon_tissue/nonIBD/174/

# For a run using SRA IDS, use the following example as a guide.
# samples:
#   - SRR5223500
#   - SRR5223505

###
# FLAGS AND OPTIONS
###

useSRA: FALSE
# True if input consists of SRA IDs.

moveOutFiles: FALSE
# Moves results files for locally run samples to permenant space.
# NOTE: set to true after running the pipeline, checking that everything
# had run correctly, and then rerun the pipeline using the same submission
# statement.
projectDir: "/proj/fureylab/projects/"
# This parameter will point to where output files such are count matrices and
# multiQC outputs will be saved for this runs

adapterTrimming: TRUE

quantification: salmon
# supports "salmon" and "rsem".

deconvolution: FALSE
# Runs deconvolution, currently set up for human colon tissue.
# NOTE: Currently missing the deconvolution rule in pipeline v1.

end: "paired"
# supports "paired" or "single"

countGeneSymbols: "tx2gene_ensembl"
# supports "tx2gene_ensembl" or "tx2gene_symbol". I recommend using ensembl
# as it is will be easier to convert to any other gene format from ensembl
# compared to gene symbols.
# NOTE: This is regarding the transcript to gene level conversion step in matrix generation.
# Instead of ensembl gene ID names, HGNC gene symbols can be generated instead.
# NOTE: This may not be available for all genomes, and so is set to ensembl by
# default. Check the software parameters section of the snakemake
# project_config.yaml file to see whether the HGNC tx2gene file is available
# for the genome of interest.

#############################
#### Software parameters ####
#############################

# https://cutadapt.readthedocs.io/en/stable/
cutadapt: # Current hard coded for Illumina TruSeq adapters. Modify -a/-A for other adapters
  a: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  A: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
  qualityCutoff: 10
  minimumLength: 20
  threads: 4

# https://raw.githubusercontent.com/alexdobin/STAR/master/doc/STARmanual.pdf
star:
  threads: 8
  genomeLoad: LoadAndRemove
  outSAMtype: "BAM SortedByCoordinate" #SAM
  quantMode: GeneCounts
  readFilesCommand: "gunzip -c"

# https://salmon.readthedocs.io/en/latest/salmon.html
salmon:
  libType: A
  threads: 8
  numBootstraps: 10
  otherFlags: "--seqBias --gcBias --validateMappings --writeUnmappedNames"

fastqc:
  threads: 1

fastq_screen:
  conf: "bin/fastq_screen.conf"
  subset: 500000
  aligner: "bowtie2"

bamCoverage:
  binSize: 10
  normalizeUsing: RPKM
  ignoreForNormalization: 'chrX chrY'

qualimap:
  seqProtocol: "non-strand-specific"
  bamqcFlags: "--collect-overlap-pairs"
  javaMemSize: "4G"

########################
#### Genome indexes ####
########################
# NOTE: hg19/hg38 STAR/SALMON INDEXES BUILT FOR PRIMARLY 50BP READS!!!
# Commands use to build these indexes are in the RNA-seq Indexing Pipeline SOP

hg19:
  salmonIndex: /proj/fureylab/genomes/human/hg19_reference/salmon_1.1.0
  starIndex: /proj/fureylab/genomes/human/hg19_reference/star_2.7.3a
  rseqcModel: /proj/fureylab/genomes/human/hg19_reference/geneModel/hg19.houseKeepingGenes.bed12
  multiqcConfig: bin/hg19/multiqc_config_hg19.yaml
  featureFile: /proj/fureylab/genomes/human/hg19_reference/RNA_annotation/gencode.v34lift37.annotation.gtf.gz
  tx2gene_ensembl: /proj/fureylab/genomes/human/hg19_reference/RNA_annotation/tx2gene.GRCh37.ENSEMBL.csv
  tx2gene_symbol: /proj/fureylab/genomes/human/hg19_reference/RNA_annotation/tx2gene.GRCh37.HGNC.csv
hg38:
  salmonIndex: /proj/fureylab/genomes/human/hg38_reference/salmon_1.2.1
  starIndex: /proj/fureylab/genomes/human/hg38_reference/star_2.7.3a
  rseqcModel: /proj/fureylab/genomes/human/hg38_reference/geneModel/hg38.houseKeepingGenes.bed12
  multiqcConfig: bin/hg38/multiqc_config_hg38.yaml
  featureFile: /proj/fureylab/genomes/human/hg38_reference/RNA_annotation/gencode.v34.annotation.gtf.gz
  tx2gene_ensembl: /proj/fureylab/genomes/human/hg38_reference/RNA_annotation/tx2gene.GRCh38.ENSEMBL.csv
  tx2gene_symbol: /proj/fureylab/genomes/human/hg38_reference/RNA_annotation/tx2gene.GRCh38.HGNC.csv
mm9:
  salmonIndex:
  starIndex:
  rseqcModel:
  multiqcConfig:
  featureFile:
  tx2gene_ensembl:
  tx2gene_symbol:
mm10:
  salmonIndex: /proj/fureylab/genomes/mouse/mm10_reference/salmon_1.2.1
  starIndex: /proj/fureylab/genomes/mouse/mm10_reference/star_2.7.3a
  rseqcModel: /proj/fureylab/genomes/mouse/mm10_reference/geneModel/houseKeepingGeneModel.bed12
  multiqcConfig: bin/mm10/multiqc_config_mm10.yaml
  featureFile: /proj/fureylab/genomes/mouse/mm10_reference/RNA_annotation/gencode.vM25.annotation.mm10.gtf.gz
  tx2gene_ensembl: /proj/fureylab/genomes/mouse/mm10_reference/RNA_annotation/tx2gene.mm10.ENSEMBL.csv
  tx2gene_symbol: /proj/fureylab/genomes/mouse/mm10_reference/RNA_annotation/tx2gene.mm10.HGNC.csv
CC027:
  salmonIndex: /proj/fureylab/genomes/mouse/CC/salmon_1.2.1/CC027
  starIndex: /proj/fureylab/genomes/mouse/CC/star_2.7.3a/CC027
  rseqcModel: /proj/fureylab/genomes/mouse/CC/geneModel/CC027.houseKeepingGenes.bed12
  multiqcConfig: bin/CC027/multiqc_config_CC027.yaml
  featureFile: /proj/fureylab/genomes/mouse/CC/RNA_annotation/gencode_vM25/CC027_gencode.vM25.annotation.randomRemoved.mm9.gtf.gz
  tx2gene_ensembl: /proj/fureylab/genomes/mouse/CC/RNA_annotation/gencode_vM25/tx2gene.CC027.ENSEMBL.csv
