######################################
#### analysis-specific parameters ####
######################################

###
# Analysis set up
###
analysis:
  name: AZ_exercise
  organism: "human" #supports "human"/"mouse"
  genomeBuild: "hg38" #supports hg38 (GRCh38) and hg19 (GRCh37)

paths:
  - /proj/fureylab/data/RNA-seq/human/colon_tissue/nonIBD/172/
  - /proj/fureylab/data/RNA-seq/human/colon_tissue/nonIBD/174/

###
# FLAGS AND OPTIONS
###

useSRA: FALSE
# True if input consists of SRA IDs.

fastqR1: TRUE
# To identify fastq files when reading local files.
# TRUE: read files contain "_R1_" or "_R2_" (e.g. *_S1_L001_R1_001.fastq.gz)
# FALSE: reads are identified by the last character (e.g. (_1.fastq.gz/_2.fastq.gz))
# NOTE: This identification of fastq files works with both *fastq.gz and *fq.gz

quantification: salmon
# supports "salmon" and "rsem".

countMatrix: TRUE
# Generates count/TPM matrix based on input samples.

deconvolution: TRUE
# Runs deconvolution, currently set up for human colon tissue.

pairedEnd: TRUE
# TRUE if input samples were sequenced paired-end

countMatrix: TRUE
# Generates count/TPM matrix based on input samples.

tx2geneSymbols: FALSE
# Regarding the transcript to gene level conversion step.
# Instead of ensembl gene ID names, HGNC gene symbols will be
# generated instead. NOTE: This is not available for all genomes,
# and so is off by default. Check the software parameters section
# of the snakemake project_config.yaml file to see whether the HGNC
# tx2gene file is available for the genome of interest.

#############################
#### Software parameters ####
#############################

# https://cutadapt.readthedocs.io/en/stable/
cutadapt: # Current hard coded for Illumina TruSeq adapters. Modify -a/-A for other adapters
  a: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  A: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
  qualityCutoff: 10
  minimumLength: 20
  threads: 4

# https://raw.githubusercontent.com/alexdobin/STAR/master/doc/STARmanual.pdf
star:
  threads: 8
  genomeLoad: LoadAndRemove
  outSAMtype: SAM #"BAM SortedByCoordinate"
  quantMode: GeneCounts
  readFilesCommand: "gunzip -c"
  sjdbOverhang: 49

# https://salmon.readthedocs.io/en/latest/salmon.html
salmon:
  libType: ISR
  threads: 8
  numBootstraps: 30
  otherFlags: "--seqBias --gcBias --validateMappings --writeUnmappedNames"

rsem:
  threads: 8
  reference: reference/hg38_rsem/rsem_hg38
  otherFlags: "--paired-end --star --output-genome-bam --keep-intermediate-files  --star-gzipped-read-file"

fastqc:
  threads: 1

fastQscreen:
  conf: "bin/fastq_screen.conf"
  subset: 1000000
  aligner: "bowtie2"

multiqc:
  configFile: bin/multiqc_config_hg38.yaml

rseqc:
  modelFile: bin/hg38.HouseKeepingGenes.bed

#genome indexes - !!! hg19/hg38 STAR/SALMON INDEXES BUILT FOR PRIMARLY 50BP READS!!!
#commands use to build these indexes are in X SOP

hg19:
  salmonIndex: /proj/fureylab/genomes/human/hg19_reference/hg19_salmon_1.1.0
  starIndex: /proj/fureylab/genomes/human/hg19_reference/hg19_star_2.7.3a
  rsemIndex: /proj/fureylab/genomes/human/hg19_reference/hg19_star_2.7.3a
  rseqcModel: /proj/fureylab/genomes/human/hg19_reference/houseKeepingGenes/hg19.HouseKeepingGenes.bed
  multiqcConfig: bin/multiqc_config_hg19.yaml
  featureFile: /proj/fureylab/genomes/human/hg19_reference/RNA_annotation/gencode.v34lift37.annotation.gtf.gz
  tx2gene_ensembl: /proj/fureylab/genomes/human/hg19_reference/RNA_annotation/tx2gene.GRCh37.ENSEMBL.csv
  tx2gene_symbol: /proj/fureylab/genomes/human/hg19_reference/RNA_annotation/tx2gene.GRCh37.HGNC.csv
hg38:
  salmonIndex: /proj/fureylab/genomes/human/hg38_reference/hg38_salmon_1.1.0
  starIndex: /proj/fureylab/genomes/human/hg38_reference/hg38_star_2.7.3a
  rsemIndex: /proj/fureylab/genomes/human/hg38_reference/hg38_star_2.7.3a
  rseqcModel: /proj/fureylab/genomes/human/hg38_reference/houseKeepingGenes/hg38.HouseKeepingGenes.bed
  multiqcConfig: bin/multiqc_config_hg38.yaml
  featureFile: /proj/fureylab/genomes/human/hg38_reference/RNA_annotation/gencode.v34.annotation.gtf.gz
  tx2gene_ensembl: /proj/fureylab/genomes/human/hg38_reference/RNA_annotation/tx2gene.GRCh38.ENSEMBL.csv
  tx2gene_symbol: /proj/fureylab/genomes/human/hg38_reference/RNA_annotation/tx2gene.GRCh38.HGNC.csv

# mouse:
#   build:
#     salmonIndex:
#     starIndex:
